name: CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '56 5 * * *'

jobs:

  testsuite:
    name: all tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4', '7.3', '7.2' ]
        TYPO3: [ '10' ]
        include:
          - TYPO3: '11'
            php: '7.4'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install testing system
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t ${{ matrix.TYPO3 }} -s composerInstall

      - name: Composer validate
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s composerValidate

      - name: Lint PHP
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s lint

      - name: CGL
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s cgl

      - name: phpstan
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t ${{ matrix.TYPO3 }} -s phpstan

      - name: Unit Tests
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s unit

      - name: Functional Tests with mariadb
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s functional

      - name: Acceptance Tests With Fluid Base Page Module on TYPO 10
        if: startsWith(matrix.TYPO3, '10')
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t ${{ matrix.TYPO3 }} -f -s acceptance -e --fail-fast

      - name: Acceptance Tests
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t ${{ matrix.TYPO3 }} -s acceptance -e --fail-fast

      - name: Archive acceptance tests results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: acceptance-test-reports-${{ matrix.php }}-${{ matrix.TYPO3 }}
          path: .Build/Web/typo3temp/var/tests/_output
